spring:
  profiles:
    active: dev
    base: com.hotent.file.controller
    title: "file"
    description: "File handle"
    version: "7.2.3"
    platform: mysql

# Server settings (ServerProperties)
server:
  port: 8084
  address: 0.0.0.0
  sessionTimeout: 30
  contextPath: /
  session:
    timeout: 30
