spring:
  profiles:
    active: dev
    base: com.hotent.system.controller
    title: "integrate"
    description: "Hotent EIP X7"
    version: "7.2.3"
    platform: mysql

# Server settings (ServerProperties)
server:
  port: 8083
  address: 0.0.0.0
  sessionTimeout: 30
  contextPath: /
  session:
    timeout: 30
