spring:
  profiles:
    active: dev
    base: com.hotent.bo.controller
    title: "@@project.name@@"
    description: "@@project.description@@"
    version: "@@project.version@@"
    platform: mysql
    
# Server settings (ServerProperties)
server:
  port: 8081
  address: 0.0.0.0
  sessionTimeout: 30
  contextPath: /
  session:
    timeout: 30