
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST';
export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST';
export const REQUEST_TYPE_LIST = 'REQUEST_TYPE_LIST';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST';

// 用户信息
export const REQUEST_USER_DETAIL = 'REQUEST_USER_DETAIL';
export const RECEIVE_USER_DETAIL = 'RECEIVE_USER_DETAIL';
export const UPDATE_USER_MESSAGE = 'UPDATE_USER_MESSAGE';

//消息
export const ON_PLAY_VOISE = 'ON_PLAY_VOISE';

//组织信息
export const REQUEST_ORG_DETAIL = 'REQUEST_ORG_DETAIL';

//常用联系人
export const REQUEST_GENERAL_CONTACT = 'REQUEST_GENERAL_CONTACT';
export const RECEIVE_GENERAL_CONTACT = 'RECEIVE_GENERAL_CONTACT';

//登录
export const LOGIN_USRE = 'LOGIN_USRE';
export const RECEIVE_LOGIN_USRE= 'RECEIVE_LOGIN_USRE';

//会话
export const REQUEST_SESSION_LIST = 'REQUEST_SESSION_LIST';
export const REQUEST_SESSION_DETAIL = 'REQUEST_SESSION_DETAIL';
export const REQUEST_MORE_MESSAGES = 'REQUEST_MORE_MESSAGES';
export const CREATE_SESSION = 'CREATE_SESSION';
export const REMOVE_SESSION = 'REMOVE_SESSION';
export const INIT_TEAMSESSION_DETAIL = 'INIT_TEAMSESSION_DETAIL';
export const RECEIVE_SESSION_JSON = 'RECEIVE_SESSION_JSON';
export const ON_OPEN_SESSION = 'ON_OPEN_SESSION';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const ON_REFRESE_UNREAD_NUM = 'ON_REFRESE_UNREAD_NUM';

//工作台
export const RECEIVE_MYREQUEST_LIST = 'RECEIVE_MYREQUEST_LIST';
export const REQUEST_GEMERALBPM_LIST = 'REQUEST_GEMERALBPM_LIST';
export const RECEIVE_MYTASK_LIST = 'RECEIVE_MYTASK_LIST';
export const RECEIVE_ALREADYMATTERS_LIST = 'RECEIVE_ALREADYMATTERS_LIST';
export const RECEIVE_MYDRAFT_LIST = 'RECEIVE_MYDRAFT_LIST';
export const RECEIVE_MYCOPYTO_LIST = 'RECEIVE_MYCOPYTO_LIST';
export const RECEIVE_MYTURNOUT_LIST = 'RECEIVE_MYTURNOUT_LIST';
export const RECEIVE_MYWORKS = 'RECEIVE_MYWORKS';
