//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpm.defxml.entity.ext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="parentDefKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="jumpType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="backMode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="backNode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="backUserMode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hideOpinion" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hidePath" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="prevHandler" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="postHandler" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="notifyType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="allowExecutorEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="skipExecutorEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="popWin" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="dateType" type="{http://www.w3.org/2001/XMLSchema}string" default="worktime" />
 *       &lt;attribute name="userNodeType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dueTime" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="initFillData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propItem")
public class PropItem {

    @XmlAttribute
    protected String help;
    @XmlAttribute
    protected String helpGlobal;
    @XmlAttribute
    protected String parentDefKey;
    @XmlAttribute
    protected String jumpType;
    @XmlAttribute
    protected String backMode;
    @XmlAttribute
    protected String backNode;
    @XmlAttribute
    protected String backUserMode;
    @XmlAttribute
    protected Boolean hideOpinion;
    @XmlAttribute
    protected Boolean hidePath;
    @XmlAttribute
    protected String prevHandler;
    @XmlAttribute
    protected String postHandler;
    @XmlAttribute
    protected String notifyType;
    @XmlAttribute
    protected Boolean allowExecutorEmpty;
    @XmlAttribute
    protected Boolean skipExecutorEmpty;
    @XmlAttribute
    protected Boolean popWin;
    @XmlAttribute
    protected String dateType;
    @XmlAttribute
    protected Integer dueTime;
    @XmlAttribute
    protected String choiceExcutor;
    @XmlAttribute
    protected Boolean allowEditUrgentState;
    
    @XmlAttribute
    protected Boolean allowSmsApproval;
    @XmlAttribute
    protected String userNodeType;
    @XmlAttribute
    protected String approvalArea="approvalOpinion,zFile,file,processRecord,imageBpm";
    @XmlAttribute
    protected Boolean referOpinion = true;
    @XmlAttribute
    protected String template;
    @XmlAttribute
    protected String phone;
    @XmlAttribute
    protected String email;
    @XmlAttribute
    protected String sendType;
    @XmlAttribute
    protected Boolean initFillData = false;
    
    /**
     * Gets the value of the parentDefKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentDefKey() {
        return parentDefKey;
    }

    /**
     * Sets the value of the parentDefKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentDefKey(String value) {
        this.parentDefKey = value;
    }

    /**
     * Gets the value of the jumpType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJumpType() {
        return jumpType;
    }

    /**
     * Sets the value of the jumpType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJumpType(String value) {
        this.jumpType = value;
    }

    /**
     * Gets the value of the backMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackMode() {
        return backMode;
    }

    /**
     * Sets the value of the backMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackMode(String value) {
        this.backMode = value;
    }

    /**
     * Gets the value of the backNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackNode() {
        return backNode;
    }

    /**
     * Sets the value of the backNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackNode(String value) {
        this.backNode = value;
    }

    /**
     * Gets the value of the backUserMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackUserMode() {
        return backUserMode;
    }

    /**
     * Sets the value of the backUserMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackUserMode(String value) {
        this.backUserMode = value;
    }

    /**
     * Gets the value of the hideOpinion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHideOpinion() {
        return hideOpinion;
    }

    /**
     * Sets the value of the hideOpinion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideOpinion(Boolean value) {
        this.hideOpinion = value;
    }

    /**
     * Gets the value of the hidePath property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHidePath() {
        return hidePath;
    }

    /**
     * Sets the value of the hidePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHidePath(Boolean value) {
        this.hidePath = value;
    }

    /**
     * Gets the value of the prevHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevHandler() {
        return prevHandler;
    }

    /**
     * Sets the value of the prevHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevHandler(String value) {
        this.prevHandler = value;
    }

    /**
     * Gets the value of the postHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostHandler() {
        return postHandler;
    }

    /**
     * Sets the value of the postHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostHandler(String value) {
        this.postHandler = value;
    }

    /**
     * Gets the value of the notifyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyType() {
        return notifyType;
    }

    /**
     * Sets the value of the notifyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyType(String value) {
        this.notifyType = value;
    }

    /**
     * Gets the value of the allowExecutorEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowExecutorEmpty() {
        if (allowExecutorEmpty == null) {
            return true;
        } else {
            return allowExecutorEmpty;
        }
    }

    /**
     * Sets the value of the allowExecutorEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowExecutorEmpty(Boolean value) {
        this.allowExecutorEmpty = value;
    }

    
    
    public Boolean getAllowEditUrgentState() {
    	 if (allowEditUrgentState == null) {
             return false;
         } else {
             return allowEditUrgentState;
         }
	}

	public void setAllowEditUrgentState(Boolean allowEditUrgentState) {
		this.allowEditUrgentState = allowEditUrgentState;
	}

	/**
     * Gets the value of the skipExecutorEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSkipExecutorEmpty() {
        if (skipExecutorEmpty == null) {
            return false;
        } else {
            return skipExecutorEmpty;
        }
    }

    /**
     * Sets the value of the skipExecutorEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSkipExecutorEmpty(Boolean value) {
        this.skipExecutorEmpty = value;
    }

    /**
     * Gets the value of the popWin property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPopWin() {
        if (popWin == null) {
            return true;
        } else {
            return popWin;
        }
    }

    /**
     * Sets the value of the popWin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPopWin(Boolean value) {
        this.popWin = value;
    }

    /**
     * Gets the value of the dateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateType() {
        if (dateType == null) {
            return "worktime";
        } else {
            return dateType;
        }
    }

    /**
     * Sets the value of the dateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateType(String value) {
        this.dateType = value;
    }

    /**
     * Gets the value of the dueTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getDueTime() {
        if (dueTime == null) {
            return  0;
        } else {
            return dueTime;
        }
    }

    /**
     * Sets the value of the dueTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDueTime(Integer value) {
        this.dueTime = value;
    }

	public String getChoiceExcutor() {
		if (choiceExcutor == null || "null".equals(choiceExcutor)) {
			return "";
		}
		return choiceExcutor;
	}

	public void setChoiceExcutor(String choiceExcutor) {
		this.choiceExcutor = choiceExcutor;
	}

    public String getHelp() {
        return help;
    }

    public void setHelp(String help) {
        this.help = help;
    }

    public String getHelpGlobal() {
        return helpGlobal;
    }

    public void setHelpGlobal(String helpGlobal) {
        this.helpGlobal = helpGlobal;
    }

	public Boolean getAllowSmsApproval() {
		if (allowSmsApproval == null || "false".equals(allowSmsApproval)) {
			return false;
		}
		return allowSmsApproval;
	}

	public void setAllowSmsApproval(Boolean allowSmsApproval) {
		this.allowSmsApproval = allowSmsApproval;
	}

	public String getUserNodeType() {
		if(userNodeType == null) {
			return "";
		}
		return userNodeType;
	}

    public String getApprovalArea() {
        return approvalArea;
    }

    public void setApprovalArea(String approvalArea) {
        this.approvalArea = approvalArea;
    }

    public void setUserNodeType(String userNodeType) {
		this.userNodeType = userNodeType;
	}

    public Boolean getReferOpinion() {
        return referOpinion;
    }

    public void setReferOpinion(Boolean referOpinion) {
        this.referOpinion = referOpinion;
    }

    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSendType() {
        return sendType;
    }

    public void setSendType(String sendType) {
        this.sendType = sendType;
    }
    /**
     * Gets the value of the initFillData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInitFillData() {
        return initFillData;
    }

    /**
     * Sets the value of the initFillData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInitFillData(Boolean value) {
        this.initFillData = value;
    }
}
